### ISSUE TITLE
Reconciliation is triggered twice while applying the same profile more than once.

### ISSUE THREAD

**Issue by snehal1797** [metal3-io/hardware-classification-controller#14]
There is one thing observed  in our testing i.e. If I apply profile ABC using kubectl ,so HCC processed profile ABC and add labels on matched hosts.  
After some time, If I change hardware parameters in Profile ABC, then apply the same.
Reconciliation is triggered twice.

########
This issue was generated because it was intentionally done in Kubernetes.(https://github.com/kubernetes-sigs/controller-runtime/issues/490)

**Comment by dhellmann** [comment]
It would help to have some more details about this. It sounds like it's doing what I would expect, because the first time Reconcile() is called the host will be updated when the labels are added and that update will trigger the watch to reconcile the host again. Then when the profile is changed the host is reconciled again. Maybe I'm misunderstanding the sequence of events that you're seeing, though?

**Comment by nehaalhat** [comment]
Here what happens is:
Scenario 1:
- First I applied profile- profile1 -> it will reconcile it and add labels if match found.
- Now I applied profile- profile2-> it reconciles profile2 twice.

Scenario 2:
- First I applied profile- profile1 -> it will reconcile it and add labels if match found.
- Now I applied profile1 again after making some changes-> it reconciles profile1 twice.

**Comment by nehaalhat** [comment]
Currently this issue is fixed in commit: c239dc6a2734041cdaa3cd678704237331a80b83

Solution I tried is using handler Funcs. This implements EventHandler for all types of events like create, update, delete. So passing this handler.Funcs {} in HWCC watcher solves this issue.

https://godoc.org/sigs.k8s.io/controller-runtime/pkg/handler#Funcs

**Comment by digambar15** [comment]
It happens like below - 

Scenario 3:

First I applied profile- profile1 -> it will reconcile it and add labels if match found.
Now I applied profile1 again after making some changes-> it reconciles profile1 twice with old and new changes

That's the weird issue we have found. What we observed that event handler is triggering event twice for watch function which ends up calling reconciller twice.

we came up with one solution to resolve the issue as there is not standard resolution to it and @nehaalhat has fixed the issue as she pointed out in her above reply. 

@dhellmann I would like you to go through the code implementation once.

**Comment by dhellmann** [comment]
> Currently this issue is fixed in commit: [c239dc6](https://github.com/metal3-io/hardware-classification-controller/commit/c239dc6a2734041cdaa3cd678704237331a80b83)

Is that commit part of a pull request?

> 
> Solution I tried is using handler Funcs. This implements EventHandler for all types of events like create, update, delete. So passing this handler.Funcs {} in HWCC watcher solves this issue.
> 
> https://godoc.org/sigs.k8s.io/controller-runtime/pkg/handler#Funcs

**Comment by nehaalhat** [comment]
> > Currently this issue is fixed in commit: [c239dc6](https://github.com/metal3-io/hardware-classification-controller/commit/c239dc6a2734041cdaa3cd678704237331a80b83)
> 
> Is that commit part of a pull request?
> 
Yes its part of PR#8: https://github.com/metal3-io/hardware-classification-controller/pull/8/commits/c239dc6a2734041cdaa3cd678704237331a80b83

**Comment by digambar15** [comment]
We don't have to add watch on HCC/BMH resources as of now. Some scenarios will come in the future, we will implement when it will be needed.
