### ISSUE TITLE
Changes required to push code of HWCC to quay.io

### ISSUE THREAD

**Issue by Ashughorla** [metal3-io/hardware-classification-controller#20]
Repository is already generated for HWCC at https://quay.io/repository/metal3-io
Modification require in Makefile and Dockerfile to use upload code at quay.io
Discussion is going to open at slack channel #cluster-api-baremetal regarding this.

**Comment by dhellmann** [comment]
According to https://quay.io/repository/metal3-io/hardware-classification-controller?tab=builds the repo is set up with a build trigger so that all new commits start an image build using `/Dockerfile` to define the image contents. I see a few different examples of updates on https://quay.io/repository/metal3-io/hardware-classification-controller?tab=history

Is there any other work to do for this ticket?

**Comment by Ashughorla** [comment]
Thanks for explanation @dhellmann.
Nothing is left with this ticket, so closing it.
